### ISSUE TITLE
Não instala na versão 5.1

### ISSUE THREAD

**Issue by marcelodelta** [artesaos/cidadesbr#3]
Olá amigo tudo bem.

Parabéns pelo pacote, bem útil. 

Você tem em mente fazer com que este pacote suporte na versão 5.1?

Abraços.

**Comment by vluzrmos** [comment]
Olá @marcelodelta ,
perdoe a demora na resposta, você pode tentar instalar a versão dev-master?
Após alguns testes lançaremos o release estável.

**Comment by vluzrmos** [comment]
Pode usar a release 1.0.2 ou 1.0.*
