### ISSUE TITLE
Class CidadeSeeder does not exist

### ISSUE THREAD

**Issue by alexandreliberato** [artesaos/cidadesbr#4]
Durante a instalação quando rodo o comando:
php artisan db:seed --class="CidadesSeeder"

É exibido o erro:
Class CidadeSeeder does not exist

 E o seed não é realizado. Engraçado que esta classe existe no meu projeto "projeto/database/seeds/CidadesSeeder.php"

Utilizo a versão 5.1.11 do Laravel.

**Comment by alexandreliberato** [comment]
Consegui! Faltou/Pulei o comando:
$ composer dump-auto

**Comment by jansenfelipe** [comment]
:+1:
